# Práctica grupal 1

## Descripción

Se dispone de la siguiente matriz donde cada elemento puede ser un número positivo, negativo o cero. 

	mat = [
		[-1, -9, 0, -1, 0],
		[-8, -3, -2, 9, -7],
		[2, 0, 0, -6, 0],
		[0, -7, -3, 5, -4]
	]

Determina el número mínimo de movimientos necesarios para convertir todos los números negativos en positivos. Solo existe una regla:

- Las celdas con números positivos  pueden convertir A números negativos en sus celdas adyacentes (i-1, j), (i+1, j), (i, j-1) e (i, j+1) (Arriba, abajo, izquierda y derecha).

Aplica el algoritmo BFS para solucionarlo

## Instrucciones

1) Crear una cola q1 y encola las coordenadas de todos los números positivos de la matriz. # q1 es para las coordenadas que faltan por descubrir

2) Crea otra cola q2 para separar los números positivos del paso actual de los del paso anterior.

3) Mientras q1 no es vacía:
    
    Copia los contenidos de la cola original q1 a la cola q2 y vacía q1
    
    Realizar hasta que q2 esté vacía # hasta que todos son positivos
       
       Obten el primer elemento de la cola q2 y comprueba las cuatro celdas adyacentes.
       
       Si alguna de las 4 celdas adyacentes es negativa, la hacemos positiva y pasamos su nuevo valor a la cola q1
    
    Incrementa el número de pasos en 1
    
4) Si todos los elementos de la cola son procesados, devolvemos el número de pasos.

## Pistas

- Podemos encontrar todas las celdas adyacentes  simplemente almacenando la posición relativa del movimiento desde cualquier posicion de la matriz. Desde cualquier posición (x,y) podemos movernos a:
   (x - 1, y)
   (x, y - 1)
   (x, y + 1)
   (x + 1, y)

##  Vuestra solución

In [1]:
from collections import deque
import math
import numpy as np

mat = [
    [-1, -9, 0, -1, 0],
    [-8, -3, -2, 9, -7],
    [2, 0, 0, -6, 0],
    [0, -7, -3, 5, -4]
]

print(np.matrix(mat))

class Point:
    
    def __init__(self, x, y, mat):
        self.x = x
        self.y = y
        self.valor = mat[x][y]
        self.cost = math.inf

    def actualizar_valor(self, valor):
        self.valor = valor

    def set_cost(self, c):
        self.cost = c

    def print(self):
        print(self.x, ',', self.y)

NORTH = Point(0, 1, mat)
SOUTH = Point(0, -1, mat)
EAST = Point(1, 0, mat)
WEST = Point(-1, 0, mat)

class Aplicar_teorema:

    def __init__(self, anchura_matriz, altura_matriz, mat):
        self.anchura_matriz = anchura_matriz
        self.altura_matriz = altura_matriz
        self._mat = mat
        self.ejercutar_busqueda_dfs()

    def ejercutar_busqueda_dfs(self):
        pasos = 0
        cola_puntos = deque()
        positivo1 = Point(2, 0, self._mat)
        positivo2 = Point(1, 3, self._mat)
        positivo3 = Point(3, 3, self._mat)
        cola_puntos.append(positivo1)
        cola_puntos.append(positivo2)
        cola_puntos.append(positivo3)

        cola_puntos_intento = deque()
        while pasos < 5:
            cola_puntos_intento = cola_puntos.copy()
            puntos_alrededores_positivos = []
            for punto in cola_puntos:    
                puntos_alrededores_positivos = self.devolver_puntos_alrededores_positivos(punto)
                for punto_alrededor in puntos_alrededores_positivos:
                    cola_puntos_intento.append(punto_alrededor)
            cola_puntos.clear()
            cola_puntos = cola_puntos_intento.copy()
            cola_puntos_intento.clear()
            pasos = pasos + 1
            print("Resultado: ")
            print(np.matrix(self._mat))
            print(f"Pasos: {pasos}")


    def devolver_puntos_alrededores_positivos(self, punto_actual):
        posiciones_alrededores = []
        posibles_alrededores = [[NORTH.x, NORTH.y], [SOUTH.x, SOUTH.y], [EAST.x, EAST.y], [WEST.x, WEST.y]]
        for punto_alrededor in posibles_alrededores: # Norte el ultimo
            if (punto_actual.x + punto_alrededor[0] <= 3 and punto_actual.y + punto_alrededor[1] <= 4):
                punto_cardinal = Point(punto_actual.x + punto_alrededor[0], punto_actual.y + punto_alrededor[1], self._mat)
                if (0 <= punto_cardinal.x < self.anchura_matriz and 0 <= punto_cardinal.y < self.altura_matriz):
                    if (self.obtener_posicion_matriz(punto_cardinal) < 0 and self.modulo_punto_actual_mayor_que_cardinal(
                        punto_actual = punto_actual, punto_cardinal = punto_cardinal) == True):
                        nuevo_valor = self.sustituir_valor_matriz(punto_cardinal)
                        punto_cardinal.actualizar_valor(nuevo_valor)
                        posiciones_alrededores.append(punto_cardinal)
        return posiciones_alrededores

    def modulo_punto_actual_mayor_que_cardinal(self, punto_actual, punto_cardinal):
        if(abs(self.obtener_posicion_matriz(punto_cardinal)) < abs(self.obtener_posicion_matriz(punto_actual))):
            return True
        else:
            return False

    def obtener_posicion_matriz(self, current_point):
        return self._mat[current_point.x][current_point.y]
    
    def sustituir_valor_matriz(self, punto_cardinal):
            self._mat[punto_cardinal.x][punto_cardinal.y] = abs(self._mat[punto_cardinal.x][punto_cardinal.y])
            return self._mat[punto_cardinal.x][punto_cardinal.y]

aplicar_dfs = Aplicar_teorema(4, 5, mat)

[[-1 -9  0 -1  0]
 [-8 -3 -2  9 -7]
 [ 2  0  0 -6  0]
 [ 0 -7 -3  5 -4]]
Resultado: 
[[-1 -9  0  1  0]
 [-8 -3  2  9  7]
 [ 2  0  0  6  0]
 [ 0 -7  3  5  4]]
Pasos: 1
Resultado: 
[[-1 -9  0  1  0]
 [-8 -3  2  9  7]
 [ 2  0  0  6  0]
 [ 0 -7  3  5  4]]
Pasos: 2
Resultado: 
[[-1 -9  0  1  0]
 [-8 -3  2  9  7]
 [ 2  0  0  6  0]
 [ 0 -7  3  5  4]]
Pasos: 3
Resultado: 
[[-1 -9  0  1  0]
 [-8 -3  2  9  7]
 [ 2  0  0  6  0]
 [ 0 -7  3  5  4]]
Pasos: 4
Resultado: 
[[-1 -9  0  1  0]
 [-8 -3  2  9  7]
 [ 2  0  0  6  0]
 [ 0 -7  3  5  4]]
Pasos: 5


¿Cuál es la complejidad de la operación en notación Big O?